name: Deploy FastAPI to Heroku

on:
  push:
    branches:
      - backend-and-ai  # triggers only on this branch

jobs:
  deploy-fastapi:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Python dependencies
      - name: Install dependencies
        working-directory: ai_analyzer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Deploy to Heroku
      - name: Deploy to Heroku
        working-directory: ai_analyzer
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add heroku https://git.heroku.com/skillmate-ai-analyzer.git
          git add .
          git commit -m "Deploy FastAPI from backend-and-ai branch"
          git push -f heroku HEAD:main
